# OpenCV

- 컴퓨터로 이미지나 영상을 읽고 이미지의 사이즈 변환이나 회전, 선분 및 도형 그리기, 채널 분리 등의 연산을 처리할 수 있도록 만들어진 오픈 소스 라이브러리
- 인텔에서 개발
- 2006년 10월 19일에 버전 1.0이 출시
- 초기에는 c언어만 지원
    - 버전 2.0부터 C++을 중심적으로 지원
    - 이후 파이썬 라이브러리로도 추가

## OpenCV의 강점

- 다양한 이미지 및 비디오 처리
    - 이미지와 비디오 데이터에 대한 다양한 처리를 간단하게 수행할 수 있음
    
- 컴퓨터 비전 알고리즘
    - 얼굴 인식, 객체 검출, 이미지 분할, 모션 추적 등의 작업을 구현하기 위한 다양한 함수와 클래스를 제공

- 머신 러닝 통합
    - 머신러닝 알고리즘을 구현하기 위한 툴도 제공
    - 텐서플로, 파이토치 등의 머신러닝 프레임워크와 통합 연계를 지원
    
- 크로스 플랫폼 지원
    - 다양한 플랫폼에서 동작하도록 설계되어 윈도우, 리눅스, macOS, 안드로이드, IOS 등에서 사용할 수 있음
    
- 오픈 소스 라이선스
    - Apache License 2.0 을 따르므로 무료로 사용할 수 있고, 소스 코드에 접근하여 필요에 따라 변경 가능
    - 상업용으로 배포하는 것도 가능
    
- 높은 성능
    - C++ 로 작성되어 빠른 속도와 효율적인 메모리 관리를 지원
    - 병렬 처리와 GPU 가속화를 활용한 높은 성능을 제공
    
- 커뮤니티 지원
    - 활발한 개발자 및 사용자 커뮤니티가 존재하여 지속적인 개발과 지원이 이루어짐
    - 새로운 기능과 업데이트가 지속적으로 이루어지며, 문제를 해결하기 위한 다양한 자료와 지원이 제공
    
- 다양한 언어 지원
    - C++, 파이썬, 자바, C# 등 다양한 언어를 지원하여 개발자들이 자신에게 편한 언어를 선택하여 사용할 수 있음
    
- 광범위한 응용 분야
    - 컴퓨터 비전과 이미지 처리 분야 뿐만 아니라 로봇, 자율 주행, 의료, 보안, 산업 등 다양한 분야에서 사용됨

# 이미지 입출력

In [43]:
# pip install opencv-python
import cv2
import numpy as np

In [2]:
image = cv2.imread("./image/like_lenna224.png", cv2.IMREAD_GRAYSCALE)

In [3]:
type(image)

numpy.ndarray

In [4]:
image.shape

(224, 224)

In [5]:
image

array([[106, 107, 107, ..., 111, 110, 111],
       [106, 107, 109, ..., 112, 111, 111],
       [107, 107, 107, ..., 112, 112, 112],
       ...,
       [ 93,  93,  95, ..., 146, 149, 149],
       [ 93,  93,  93, ..., 146, 146, 147],
       [ 92,  92,  93, ..., 146, 147, 147]], dtype=uint8)

- 이미지를 구성하는 숫자들은 그 수가 매우 많기 때문에 효율적으로 저장하고 관리해야 함
    - 이미지 전체 픽셀에 대해 연산을 해야하는 상황처럼 연산량이 많아진다면 numpy.ndarray를 사용해야 속도가 빠르고, 더 적은 메모리 공간을 차지할 수 있음

In [6]:
cv2.imshow("img", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 이미지 변환

## 사이즈 변환

- cv2.resize()
    - 인수
        - src : 입력 이미지 혹은 입력 영상을 입력
        - dsize : 변환 후 이미지의 형태
            - (가로의 길이, 세로의 길이) 형식으로 튜플로 입력
        - ds : 출력 이미지를 저장할 numpy.ndarray 변수를 입력
        - fx, fy : 입력 이미지와 출력 이미지의 배율
            - 해당 인수를 사용하기 위해서는 dsize 인수에 None값을 대입
        - interpoloation : 이미지를 확대할 때 비어있는 픽셀을 채울 규칙을 지정

In [7]:
image_small = cv2.resize(image, (100, 100))

In [9]:
image_small.shape

(100, 100)

In [11]:
cv2.imshow("image", image_small)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# 배율 지정 방식
image_big = cv2.resize(image, dsize = None, fx = 2, fy =2)

In [13]:
image_big.shape

(448, 448)

In [21]:
cv2.imshow("", image_big)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 대칭 변환

- 이미지를 수평, 수직 또는 두 축 모두에 대해 반전시키는 작업
- OpenCV에서는 cv2.flip() 함수를 사용하여 이미지를 대칭, 변환할 수 있음
    - flip 함수는 image변수와 대칭으로 돌릴 축을 0, 1 등으로 명시하여 변환을 수행
        - 0 : 수평축 반전
        - 1 : 수직축 반전

In [22]:
# 수평축 반전
image_fliped = cv2.flip(image, 0)
cv2.imshow("", image_fliped)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
# 수직축 반전
image_fliped2 = cv2.flip(image, 1)
cv2.imshow("", image_fliped2)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 회전 변환

- 이미지를 주어진 각도만큼 회전시키는 작업
- cv2.getRotationMatrix2D 함수를 사용하여 회전 변환 행렬을 생성하고
    - center : 어떤 점을 기준으로 회전시킬지 지정
    - angle : 얼마나 회전시킬지 지정
    - scale : 결과 이미지의 배율을 어떻게 할 지 지정
    
- cv2.warpAffine 함수를 사용하여 실제로 이미지를 회전
    - 앞에서 만들어진 변환 행렬과 이미지를 받아 실제 변환을 수행

In [25]:
height, width = image.shape
matrix = cv2.getRotationMatrix2D((width / 2, height / 2), 90, 1)

In [26]:
matrix

array([[ 6.12323400e-17,  1.00000000e+00, -1.42108547e-14],
       [-1.00000000e+00,  6.12323400e-17,  2.24000000e+02]])

In [28]:
result = cv2.warpAffine(image, matrix, (width, height))
cv2.imshow("", result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [34]:
# 30도 회전
matrix = cv2.getRotationMatrix2D((width / 2, height / 2), 30, 1)
result2 = cv2.warpAffine(image, matrix, (width, height), borderValue = 200)
cv2.imshow("", result2)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 자르기

- 이미지 자르기 기능은 파이썬의 슬라이싱 기능을 사용

In [35]:
cv2.imshow("", image[:100, :100])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [36]:
# 가로, 세로 모두 51번째 픽셀부터 150번째 픽셀까지 자르기
cv2.imshow("", image[50:150, 50:150])
cv2.waitKey(0)
cv2.destroyAllWindows()

- numpy.ndarray 의 슬라이싱은 원본 객체의 값을 그대로 참조
    - 할당되어 있는 픽셀의 숫자 값을 바꿔주면 원본의 픽샐 값이 함께 변화

In [37]:
croped_image = image[50:150, 50:150]
croped_image[:] = 200

In [39]:
cv2.imshow("", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

- 이미지 일부를 잘라서 변화를 주고 싶지만 원본 이미지에 영향을 미치고 싶지 않을 때는 자른 객체에 대한 깊은 복사를 사용해야 함

In [40]:
image = cv2.imread("./image/like_lenna224.png", cv2.IMREAD_GRAYSCALE)
croped_image = image[50:150, 50:150].copy() # 깊은 복사
croped_image[:] = 200

In [41]:
cv2.imshow("", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [42]:
cv2.imshow("", croped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 도형 그리기

- OpenCV는 읽어온 이미지 위애 원하는 도형을 그릴 수 있는 기능을 제공
- 이 기능을 사용해 이미지 위에 객체를 구분하는 박스를 그리거나 글씨를 쓰는 일 등의 작업을 수행

- 자주 사용하는 기능과 함수
    - 선 그리기 : cv2.line
    - 원 그리기 : cv2.circle
    - 직사각형 그리기 : cv2.rectangle
    - 타원 그리기 : cv2.ellipse
    - 다각형 그리기 : cv2.polylines, cv2.fillPoly

### 선 그리기(cv2.line)

- 이미지와 두 개의 점을 받아서 이어줌
    - color, thickness 등의 옵션으로 선을 다양하게 그려볼 수 있음

In [44]:
space = np.zeros((500, 1000), dtype = np.uint8)

In [45]:
space.shape

(500, 1000)

In [46]:
space

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [48]:
line_color = 255
space = cv2.line(space, (100, 100), (800, 400), line_color, 3, 1)

In [49]:
cv2.imshow("", space)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 원 그리기(cv2.circle)

- 원의 중심 좌표와 반지름 값을 받아 원 그리기

In [56]:
space2 = np.zeros((500, 1000), dtype = np.uint8)
color = 255
space2 = cv2.circle(space2, (600, 200), 100, color, 4, 1)

In [57]:
cv2.imshow("", space2)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 직사각형 그리기(cv2.rectangle)

- 객체 탐지에서 특정 대상이 있을 때, 상자 표시로 해당 대상을 나타내는 데 사용하는 기능
- 이미지와 두 개의 좌표를 받아 이미지 위애 직사각형을 그려줌
    - 두 개의 좌표(pt1, pt2)는 각각 사각형의 왼쪽 위와 오른쪽 아래의 꼭짓점 좌표를 의미

In [58]:
space3 = np.zeros((768, 1388), dtype = np.uint8)
line_color = 255
space3 = cv2.rectangle(space3, (500, 200), (800, 400), line_color, 5, 1)

In [59]:
cv2.imshow("", space3)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 타원 그리기(cv2.ellipse)

- 이미지와 타원의 중심 및 축, 축의 각도, 타원을 그릴 각도(시작점과 끝점)를 받아 이미지 위에 원하는 타원을 그림
    - certer : 타원 중심의 좌표
    - axes : 축의 좌표
    - angle : 타원 축의 각도
    - startAngle : 타원을 그리기 시작할 각도 값
    - endAngle : 타원 그리기를 끝낼 각도
    - color : 색상(숫자로 기입)
    - thickness : 선의 두께

In [61]:
space4 = np.zeros((768, 1388), dtype = np.uint8)
line_color = 255
space4 = cv2.ellipse(space4, (500, 300), (300, 200), 0, 90, 250, line_color, 4)

In [62]:
cv2.imshow("", space4)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 다각형 그리기(cv2.polylines, cv2.fillPoly)
.
- cv2.polylines : 여러 점을 잇는 선을 그려서 다각형을 그림
- cv2.fillPoly : 색칠된 면을 갖는 다각형을 그림

In [63]:
space5 = np.zeros((768, 1388), dtype = np.uint8)
color = 255
obj1 = np.array([[300, 500], [500, 500], [400, 600], [200, 600]])
obj2 = np.array([[600, 500], [800, 500], [700, 200]])

space5 = cv2.polylines(space5, [obj1], True, color, 3)
space5 = cv2.fillPoly(space5, [obj2], color, 1)

In [64]:
cv2.imshow("", space5)
cv2.waitKey(0)
cv2.destroyAllWindows()