In [1]:
import numpy as np

# 넘파이 배열의 구조

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array; 다차원배열)

In [2]:
# 리스트를 다차원배열로 변환
# array() : 다차원배열을 만드는 함수
li = [1, 2, 3, 4]
li_arr = np.array(li)

In [3]:
li_arr

array([1, 2, 3, 4])

In [4]:
type(li_arr)

numpy.ndarray

In [5]:
# 튜플을 다차원배열로 변환
tu = (1, 2, 3, 4)
tu_arr = np.array(tu)

In [6]:
tu_arr

array([1, 2, 3, 4])

In [7]:
type(tu_arr)

numpy.ndarray

In [8]:
# 배열도 mutable의 특징을 가짐
# 변수를 다른 변수에 복사한 뒤 데이터를 수정하면 모든 변수의 데이터가 수정됨
co_arr = li_arr
id(co_arr), id(li_arr)

(1821508696080, 1821508696080)

In [9]:
co_arr[0] = 100
co_arr

array([100,   2,   3,   4])

In [10]:
li_arr

array([100,   2,   3,   4])

In [11]:
# 다차원 배열의 값을 복사해서 새로운 배열을 만들면
# 동일한 값을 가진 새로운 배열을 만들기 때문에 서로 다른 데이터가 됨
new_arr = np.array(li_arr)

In [12]:
id(new_arr), id(li_arr)

(1821513802512, 1821508696080)

In [13]:
new_arr[0] = 99
new_arr

array([99,  2,  3,  4])

In [14]:
li_arr

array([100,   2,   3,   4])

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만 넘파이 배열은 같은 자료형만 넣을 수 있음
    - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추론해서 만듦

In [15]:
# float 자료형을 지정해서 다차원 배열 만들기
fl_arr = np.array(li, dtype = float)
fl_arr

array([1., 2., 3., 4.])

In [16]:
fl_arr.dtype

dtype('float64')

## 2차원 배열

- 2개의 축을 가지는 배열(행, 열)
    - 두 개 이상의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐

In [17]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# 각 축의 원소의 개수
arr2d.shape

(2, 3)

In [19]:
# 축의 개수
arr2d.ndim

2

In [20]:
arr2d.dtype

dtype('int32')

In [21]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

## 원소 조회하기

In [22]:
# 1차원 배열에서 원소 조회
li_arr

array([100,   2,   3,   4])

In [23]:
li

[1, 2, 3, 4]

In [24]:
li_arr[0]

100

In [25]:
li[0]

1

In [26]:
# 다차원 배열에서 원소 조회
list2d = arr2d.tolist() # 배열을 리스트로 변환

In [27]:
list2d

[[1, 2, 3], [4, 5, 6]]

In [28]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# 리스트는 정수만 이용해서 원소 조회 가능
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱스를 두 번 사용해야함
list2d[0]

[1, 2, 3]

In [30]:
list2d[0][1]

2

In [31]:
list2d[0, 1]

TypeError: list indices must be integers or slices, not tuple

In [32]:
# 다차원 배열은 행과 열의 인덱스를 튜플로 조회할 수 있음
arr2d[0, 1]

2

In [33]:
arr2d[0][1]

2

### 슬라이싱

In [34]:
arr1 = np.array([[0, 1, 2, 3,], [4, 5, 6, 7]])
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
# 첫 번째 행 전체
arr1[0 , :]

array([0, 1, 2, 3])

In [36]:
# 두 번째 열 전체
arr1[:, 1]

array([1, 5])

In [37]:
# 두 번째 행의 두 번째 열부터 끝열까지
arr1[1, 1:]

array([5, 6, 7])

In [38]:
# 각 행의 두 번째 열까지
arr1[:, :2]

array([[0, 1],
       [4, 5]])

#### 연습문제

1. 아래의 행렬에서 값 7을 인덱싱
2. 아래의 행렬에서 값 14를 인덱싱
3. 아래의 행렬에서 배열 [6, 7]을 슬라이싱
4. 아래의 행렬에서 배열 [7, 12]를 슬라이싱
5. 아래의 행렬에서 배열 [[3, 4], [8, 9]]를 슬라이싱

In [39]:
m = np.array([[0, 1, 2, 3, 4],
             [5, 6, 7, 8, 9],
             [10, 11, 12, 13, 14]])

In [40]:
print(m[1,2])
print(m[2,4], m[-1, -1])
print(m[1, 1:3])
print(m[1:, 2])
print(m[:2, 3:])

7
14 14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [41]:
m = np.array([[[1, 2, 3], [4, 5, 6]],
             [[7, 8, 9], [10, 11, 12]],
             [[13, 14, 15], [16, 17, 18]],
             [[19, 20, 21], [22, 23, 24]]])

1. [8, 14] 슬라이싱
2. [[11, 12], [17, 18]] 슬라이싱
3. [3, 9, 15, 21] 슬라이싱

In [42]:
print("1.", m[1:3, 0, 1])
print("2.", m[1:3, 1, 1:])
print("3.", m[:, 0, 2])

1. [ 8 14]
2. [[11 12]
 [17 18]]
3. [ 3  9 15 21]


## 파이썬 리스트와 넘파이 배열의 차이

- 넘파이 배열은 배열끼리 연산이 가능하지만 파이썬 리스트는 값의 추가만 가능
- 넘파이 배열은 숫자와의 연산도 가능하지만 파이썬 리스트는 불가능
    - 파이썬 리스트 : 곱셈으로 리스트 요소를 반복하는 것은 가능
    
- 사용 용도
    - 파이썬 리스트는 값을 추가하거나 제거하는 일에 사용
    - 넘파이 배열은 수치 계산이 많고 복잡하거나 다차원 배열이 필요할 때 사용

# 전치 연산(transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [43]:
arr= np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr.shape

(2, 3)

In [45]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
arr.T.shape

(3, 2)

# 배열 크기 변형

In [47]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
arr2 = arr1.reshape(3, 4)

In [49]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 사용하는 원소의 수가 정해져 있기 때문에 reshape의 형태 원소중 하나는 -1로 대체할 수 있음

In [50]:
arr1.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
arr1.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [52]:
arr1.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# 넘파이 함수의 특징

- 벡터화 연산
    - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
    - 동일한 인덱스의 원소끼리 계산을 처리하는 것을 벡터화 연산이라고 함
    
- 유니버셜 함수(universal function)
    - 벡터화 연산을 지원하는 특별한 함수를 유니버설 함수라고 함

In [53]:
# 일반 파이썬 함수의 타입 확인
def test():
    pass

In [54]:
type(test)

function

In [55]:
# 유니버설 함수 확인
type(np.add)

numpy.ufunc

In [56]:
# 넘파이 모듈에는 유니버설 함수도 있고 일반 함수도 있음
type(np.sort)

function

In [57]:
list2d

[[1, 2, 3], [4, 5, 6]]

In [58]:
list2d + list2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [59]:
np.add(list2d, list2d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 벡터화 연산

### 벡터화 연산이 필요한 이유

- data 리스트 내의 각 값에 2를 곱해야 하는 경우

In [60]:
# 리스트를 통한 풀이
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [61]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
ans = []

for i in data:
    ans.append(i * 2)
    
ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [63]:
# 넘파이를 통한 풀이
data = np.array(data)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 넘파이 벡터화 연산

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [65]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [66]:
2 * a + b

array([12, 24, 36])

In [67]:
a == 2

array([False,  True, False])

In [68]:
[1, 2, 3] == 2

False

In [69]:
b > 10

array([False,  True,  True])

In [70]:
(a == 2) & (b > 10)

array([False,  True, False])

In [71]:
a

array([1, 2, 3])

In [72]:
a[[True, False, True]]

array([1, 3])

In [73]:
a[a == 2]

array([2])

- 배열끼리의 연산

In [74]:
arr1 = np.arange(6, 10)
arr1

array([6, 7, 8, 9])

In [75]:
arr2 = np.arange(10, 14)
arr2

array([10, 11, 12, 13])

In [76]:
# 두 개의 다차원 배열을 곱하면 동일한 인덱스의 원소끼리 곱셈한 결과인 1차원 배열이 반환됨
arr1 * arr2

array([ 60,  77,  96, 117])

In [77]:
# arr1에 차원 추가(수직축 추가)
new_arr1 = arr1.reshape(-1, 1)
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [78]:
new_arr1.shape

(4, 1)

In [80]:
# arr2에 차원 추가(수평축 추가)
new_arr2 = arr2.reshape(1, -1)
new_arr2

array([[10, 11, 12, 13]])

In [81]:
new_arr2.shape

(1, 4)

## 브로드캐스팅(broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야 함
- 서로 다른 크기를 가진 배열의 사직 연찬승ㄹ 하는 경우 넘파이에서는 크기가 작은 배열을 자동으로 반복확장하여 크기가 큰 배열에 맞춤

In [82]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

In [83]:
# 행렬곱 연산
new_arr1 * new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [84]:
new_arr1 @ new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [85]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [86]:
a

array([[1, 2],
       [3, 4]])

In [87]:
b

array([[5, 6],
       [7, 8]])

In [88]:
# * 연산자는 요소별 곱셈을 수행
a * b

array([[ 5, 12],
       [21, 32]])

In [89]:
# @ 연산자는 행렬 곱셈을 수행
a @ b

array([[19, 22],
       [43, 50]])

#### 연습문제

1. 아래의 배열에서 3의 배수를 찾기
2. 아래의 배열에서 4로 나누면 1이 남는 수 찾기
3. 아래의 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기

In [90]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [98]:
x[x % 3 == 0], x[2::3]

(array([ 3,  6,  9, 12, 15, 18]), array([ 3,  6,  9, 12, 15, 18]))

In [93]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [94]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

## 축에따른 연산
    
- 동일한 축에 있는 원소들을 계산하기 위해서 필요

In [99]:
# 1차원 배열
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [100]:
#합계
np.sum(arr1)

10

In [101]:
arr1.sum()

10

In [102]:
# 최댓값
arr1.max()

4

In [103]:
# 최솟값
arr1.min()

1

In [105]:
# 최솟밗의 위치
arr1.argmin()

0

In [104]:
# 최댓값의 위치
arr1.argmax()

3

In [106]:
# 평균
arr1.mean()

2.5

In [107]:
# 중앙값
np.median(arr1)

2.5

In [108]:
# 2차원 배열
arr2 = arr1.reshape(2, 2)
arr2

array([[1, 2],
       [3, 4]])

In [109]:
# 모든 원소를 더한 합
np.sum(arr2)

10

In [110]:
# 수직방향으로 같은 열에 속한 원소만 합산
np.sum(arr2, axis = 0)

array([4, 6])

In [111]:
# 수평방향으로 같은 행에 속한 원소만 합산
np.sum(arr2, axis = 1)

array([3, 7])

In [112]:
# 3차원 배열
arr3 = np.arange(1, 9)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
arr4 = arr3.reshape(2, 2, 2)
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [114]:
# 모든 원소를 더한 합
np.sum(arr4)

36

In [115]:
# 두 개의 행렬의 동일한 인덱스의 원소를 합한 값
np.sum(arr4, axis = 0)

array([[ 6,  8],
       [10, 12]])

In [116]:
# 각 2차원 배열의 0번축(열)의 합
np.sum(arr4, axis = 1)

array([[ 4,  6],
       [12, 14]])

In [117]:
# 각 2차원 배열의 1번축(행)의 합
np.sum(arr4, axis = 2)

array([[ 3,  7],
       [11, 15]])

#### 연습문제

1. 전체의 최대값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

In [119]:
x = np.random.random((5, 6))

In [122]:
x

array([[0.12322489, 0.22053346, 0.07607474, 0.82236131, 0.42464008,
        0.01587844],
       [0.35668981, 0.18669288, 0.97640452, 0.12280467, 0.55833756,
        0.96799441],
       [0.1681675 , 0.82023496, 0.55394441, 0.43302262, 0.64167892,
        0.44924884],
       [0.50035   , 0.12493787, 0.14409548, 0.03836178, 0.61956364,
        0.91713043],
       [0.56665537, 0.21802604, 0.6478836 , 0.81904471, 0.50573854,
        0.57958631]])

In [135]:
np.max(x), np.sum(x, axis = 1), np.max(x, axis = 1), np.mean(x, axis = 0), np.min(x, axis = 0)

(0.9764045219722645,
 array([1.68271291, 3.16892384, 3.06629725, 2.34443919, 3.33693457]),
 array([0.82236131, 0.97640452, 0.82023496, 0.91713043, 0.81904471]),
 array([0.34301751, 0.31408504, 0.47968055, 0.44711902, 0.54999175,
        0.58596769]),
 array([0.12322489, 0.12493787, 0.07607474, 0.03836178, 0.42464008,
        0.01587844]))

In [136]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [137]:
arr4.sum(axis = 0)

array([[ 6,  8],
       [10, 12]])

In [138]:
arr4.sum(axis = 1)

array([[ 4,  6],
       [12, 14]])

In [139]:
arr4.sum(axis = 2)

array([[ 3,  7],
       [11, 15]])

In [140]:
arr4.sum(axis = (0, 1))

array([16, 20])

In [141]:
arr4.sum(axis = (0, 2))

array([14, 22])

In [142]:
arr4.sum(axis = (1, 2))

array([10, 26])

In [144]:
arr5 = np.random.randint(0, 3, (2, 3, 4))
arr5

array([[[0, 2, 2, 0],
        [0, 1, 2, 0],
        [0, 0, 2, 1]],

       [[1, 1, 2, 1],
        [1, 1, 0, 0],
        [1, 0, 0, 2]]])

In [145]:
arr5.sum(axis = 0)

array([[1, 3, 4, 1],
       [1, 2, 2, 0],
       [1, 0, 2, 3]])

In [146]:
arr5.sum(axis = 1)

array([[0, 3, 6, 1],
       [3, 2, 2, 3]])

In [147]:
arr5.mean(axis = 2)

array([[1.  , 0.75, 0.75],
       [1.25, 0.5 , 0.75]])

In [149]:
arr5.mean(axis = (0, 1))

array([0.5       , 0.83333333, 1.33333333, 0.66666667])

In [150]:
arr5.mean(axis = (0, 2))

array([1.125, 0.625, 0.75 ])

In [151]:
arr5.mean(axis = (1, 2))

array([0.83333333, 0.83333333])

In [152]:
data_3d = np.random.random((3, 5, 6))
data_3d

array([[[0.36905176, 0.41955628, 0.98825182, 0.08775995, 0.31339876,
         0.23881689],
        [0.34294259, 0.46730376, 0.61776843, 0.14771895, 0.39227653,
         0.71903787],
        [0.82531036, 0.28230329, 0.19806757, 0.85058453, 0.34525733,
         0.66169846],
        [0.22774236, 0.82538335, 0.44279289, 0.59090442, 0.27769421,
         0.04831374],
        [0.18080738, 0.02407945, 0.45108052, 0.47574736, 0.36256409,
         0.83626601]],

       [[0.62127148, 0.58486678, 0.6095499 , 0.58617464, 0.53797047,
         0.03286187],
        [0.46446335, 0.4316139 , 0.46200398, 0.08690196, 0.22084023,
         0.4201708 ],
        [0.11160595, 0.41182021, 0.16535725, 0.42367294, 0.21908798,
         0.17653631],
        [0.89937787, 0.04287351, 0.75374854, 0.66583382, 0.0149478 ,
         0.78722076],
        [0.52742149, 0.87893093, 0.55467893, 0.24152179, 0.8426277 ,
         0.59909408]],

       [[0.33585475, 0.05362721, 0.502653  , 0.11469645, 0.86236752,
         0.682077

In [156]:
data_3d.shape

(3, 5, 6)

1. 각 2차원 배열에서의 최댓값
2. 각 2차원 배열에서의 행의 합
3. 각 2차원 배열에서의 각 행의 최댓값
4. 전체 열의 평균
5. 각 2차원 배열에서의 열의 평균
6. 각 2차원 배열에서의 각 열의 최솟값

In [166]:
data_3d

array([[[0.36905176, 0.41955628, 0.98825182, 0.08775995, 0.31339876,
         0.23881689],
        [0.34294259, 0.46730376, 0.61776843, 0.14771895, 0.39227653,
         0.71903787],
        [0.82531036, 0.28230329, 0.19806757, 0.85058453, 0.34525733,
         0.66169846],
        [0.22774236, 0.82538335, 0.44279289, 0.59090442, 0.27769421,
         0.04831374],
        [0.18080738, 0.02407945, 0.45108052, 0.47574736, 0.36256409,
         0.83626601]],

       [[0.62127148, 0.58486678, 0.6095499 , 0.58617464, 0.53797047,
         0.03286187],
        [0.46446335, 0.4316139 , 0.46200398, 0.08690196, 0.22084023,
         0.4201708 ],
        [0.11160595, 0.41182021, 0.16535725, 0.42367294, 0.21908798,
         0.17653631],
        [0.89937787, 0.04287351, 0.75374854, 0.66583382, 0.0149478 ,
         0.78722076],
        [0.52742149, 0.87893093, 0.55467893, 0.24152179, 0.8426277 ,
         0.59909408]],

       [[0.33585475, 0.05362721, 0.502653  , 0.11469645, 0.86236752,
         0.682077

In [167]:
data_3d.max(axis = (1, 2))

array([0.98825182, 0.89937787, 0.99908225])

In [165]:
data_3d.sum(axis = 2)

array([[2.41683546, 2.68704813, 3.16322153, 2.41283096, 2.33054481],
       [2.97269514, 2.08599421, 1.50808063, 3.1640023 , 3.64427492],
       [2.5512767 , 3.7473394 , 2.85483656, 3.0700889 , 3.82984911]])

In [164]:
data_3d.max(axis = 2)

array([[0.98825182, 0.71903787, 0.85058453, 0.82538335, 0.83626601],
       [0.62127148, 0.46446335, 0.42367294, 0.89937787, 0.87893093],
       [0.86236752, 0.83759676, 0.70618658, 0.88170862, 0.99908225]])

In [160]:
data_3d.mean(axis = (0, 1))

array([0.51378421, 0.40678437, 0.5604879 , 0.39760363, 0.47538454,
       0.4752166 ])

In [169]:
data_3d.mean(axis =  1)

array([[0.38917089, 0.40372523, 0.53959224, 0.43054304, 0.33823818,
        0.50082659],
       [0.52482803, 0.47002106, 0.50906772, 0.40082103, 0.36709484,
        0.40317676],
       [0.62735371, 0.34660681, 0.63280374, 0.36144683, 0.7208206 ,
        0.52164644]])

In [163]:
data_3d.min(axis = 1)

array([[0.18080738, 0.02407945, 0.19806757, 0.08775995, 0.27769421,
        0.04831374],
       [0.11160595, 0.04287351, 0.16535725, 0.08690196, 0.0149478 ,
        0.03286187],
       [0.33585475, 0.05362721, 0.502653  , 0.11469645, 0.32678871,
        0.12862702]])

# inf 와 nan

- 넘파이에서는 무한대를 표현하기 위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan 이 있음

In [174]:
1 / 0

ZeroDivisionError: division by zero

In [175]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\sungj\AppData\Local\Temp\ipykernel_7924\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\sungj\AppData\Local\Temp\ipykernel_7924\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])